### ISSUE TITLE
Logo proposal: Monica

### ISSUE THREAD

**Issue by baranpirincal** [zalf-rpm/monica#14]
Hey, I examined your project and I want to contribute on your project with making a logo design. I did not see any logo design on description of your project, I guess only an simple icon you have. What do you think about it? 

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by bergm** [comment]
Hi,
for MONICA, the model this repository is about, we actually even got a logo, but it's only used as an icon for the program when installed. But feel free to make a proposal. 👍 
It's a research project, but open source, so we're happy about people contributing, whatever they have to offer. :-)

cheers
Michael

**Comment by bergm** [comment]
Dear @baranpirincal,
thank you for your logo proposal. It looks indeed interesting, but after some discussion with my colleagues, we think we will stick with our current logo, which also is already established. We very much value your contribution, but also don't want to waste your time in further proposals. But we will certainly keep you in mind if we need ideas for something new. 
Thanks again for your work and effort. 
The MONICA team.
