### ISSUE TITLE
MONICA parameters at two different locations

### ISSUE THREAD

**Issue by cnendel** [zalf-rpm/monica#18]
After installation of version 2.1.1 I find a folder "monica-parameters" both at the work directory C:\ZALF and in the user directory C:\users\person\MONICA. I assume that only one is valid?

**Comment by sannyschulz** [comment]
Not an issue:

One is the checkout from git (e.g. in C:\ZALF ) and one is the installed version ( e.g. in 'C:\users\person\MONICA')
During the installation process the environment variables MONICA_HOME and MONICA_PARAMETERS will be created, which will point by default to the installed version in your user account, e.g. 'C:\users\person\MONICA' 
You may adjust the environment variables to point to any directory you want to use.
