### ISSUE TITLE
Build docker image with MONICA fails

### ISSUE THREAD

**Issue by mishagrol** [zalf-rpm/monica#28]
Hello, @bergm ! 👋

Trying install MONICA into docker (Debian) using Dockerfile: https://github.com/zalf-rpm/monica/blob/master/Dockerfile

However, build fails with error related to MAS repo
```
CMake Error at /resource/vcpkg/scripts/buildsystems/vcpkg.cmake:623 (_add_library):
#32 3.462   Cannot find source file:
#32 3.462 
#32 3.462     /resource/mas-infrastructure/src/cpp/common/rpc-connections.h
```

Looks like `rpc-connections.h` file moved to `https://github.com/zalf-rpm/mas-infrastructure/blob/master/src/cpp/common/restorable-service-main.h`

Link to log file of docker build: https://drive.google.com/file/d/1HhkGck9X4uxPtHk1MUKiUAWEW1lDCRep/view?usp=share_link

Maybe there is stable version to build or even docker image in docker-hub?

Thank you! 🍀

**Comment by bergm** [comment]
Hi @mishagrol,
thanks for pointing me to this. I'll try to fix it today and report here, if it works again.
Cheers, Michael

**Comment by bergm** [comment]
> Hi @mishagrol,
> thanks for pointing me to this. I'll try to fix it today and report here, if it works again.
> Cheers, Michael

Just as an update. 🙈 I messed around to fix the issue, breaking even more and ran out of time to get every thing in order. I hope to have everything cleaned up on Monday and MONICA will build again.

**Comment by bergm** [comment]
Hello @mishagrol ,
you should be able to create a docker image now. Cleaning up took longer than expected, but at least I simplified some things in the MONICA build process and improved the cmake builds. I pushed a current build to DockerHub. (docker pull zalfrpm/monica-cluster:3.4.0.212)
If you encounter any problems, please let me know.
Cheers, Michael
